name: Deploy Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install -g serve

      - name: Build
        run: |
          echo "No build step required for static website"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages

      - name: Run Tests
        run: |
          echo "Running basic tests..."
          # Add your test commands here if needed

      - name: Notify on Success
        if: success()
        run: |
          echo "Deployment completed successfully!"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment failed!" 